function resolver_inecuacion_gui()
    % Interfaz gráfica simple para resolver_inecuacion()
    
    % Crear la figura principal
    fig = uifigure('Name', 'Resolución de Inecuaciones', ...
                   'Position', [300, 200, 600, 400], ...
                   'Resize', 'off', ...
                   'Color', [0.95, 0.95, 0.95]);
    
    % Título principal
    titulo = uilabel(fig, 'Text', 'RESOLUCIÓN DE INECUACIONES', ...
                     'Position', [50, 340, 500, 35], ...
                     'FontSize', 20, ...
                     'FontWeight', 'bold', ...
                     'HorizontalAlignment', 'center', ...
                     'BackgroundColor', [0.2, 0.4, 0.7], ...
                     'FontColor', 'white');
    
    % Descripción
    descripcion = uilabel(fig, 'Text', 'Esta herramienta resuelve inecuaciones lineales y cuadráticas.', ...
                          'Position', [50, 300, 500, 25], ...
                          'FontSize', 12, ...
                          'HorizontalAlignment', 'center', ...
                          'FontColor', [0.3, 0.3, 0.3]);
    
    % Panel de opciones
    panel_opciones = uipanel(fig, 'Title', 'Tipos de inecuaciones disponibles', ...
                             'Position', [50, 150, 500, 140], ...
                             'FontSize', 12, ...
                             'FontWeight', 'bold', ...
                             'BackgroundColor', [0.98, 0.98, 1]);
    
    % Botones de opciones
    btn_lineal = uibutton(panel_opciones, 'Text', '1. Inecuación lineal (ax + b < 0)', ...
                          'Position', [50, 80, 400, 35], ...
                          'FontSize', 14, ...
                          'HorizontalAlignment', 'left', ...
                          'BackgroundColor', [0.2, 0.7, 0.2], ...
                          'FontColor', 'white', ...
                          'ButtonPushedFcn', @(~,~) ejecutar_opcion(1));
    
    btn_cuadratica = uibutton(panel_opciones, 'Text', '2. Inecuación cuadrática (ax² + bx + c < 0)', ...
                              'Position', [50, 35, 400, 35], ...
                              'FontSize', 14, ...
                              'HorizontalAlignment', 'left', ...
                              'BackgroundColor', [0.7, 0.2, 0.7], ...
                              'FontColor', 'white', ...
                              'ButtonPushedFcn', @(~,~) ejecutar_opcion(2));
    
    % Botón de salir
    btn_salir = uibutton(fig, 'Text', '0. Volver al menú principal', ...
                         'Position', [200, 100, 200, 35], ...
                         'FontSize', 12, ...
                         'BackgroundColor', [0.7, 0.7, 0.7], ...
                         'FontColor', 'white', ...
                         'ButtonPushedFcn', @(~,~) close(fig));
    
    % Panel de mensajes
    panel_mensajes = uipanel(fig, 'Title', 'Mensajes', ...
                             'Position', [50, 20, 500, 70], ...
                             'FontSize', 10, ...
                             'BackgroundColor', [0.98, 0.98, 0.98]);
    
    texto_mensaje = uilabel(panel_mensajes, ...
                            'Text', 'Seleccione una opción para continuar...', ...
                            'Position', [10, 10, 480, 30], ...
                            'FontSize', 11, ...
                            'HorizontalAlignment', 'center', ...
                            'FontColor', [0.4, 0.4, 0.4]);
    
    % Función para ejecutar las opciones
    function ejecutar_opcion(opcion)
        switch opcion
            case 1
                texto_mensaje.Text = 'Ejecutando inecuación lineal...';
                texto_mensaje.FontColor = [0.2, 0.7, 0.2];
                drawnow;
                try
                    inecuacion_lineal();
                    texto_mensaje.Text = 'Inecuación lineal completada.';
                catch
                    texto_mensaje.Text = 'Error: Función inecuacion_lineal() no encontrada.';
                    texto_mensaje.FontColor = [0.8, 0.2, 0.2];
                end
                
            case 2
                texto_mensaje.Text = 'Ejecutando inecuación cuadrática...';
                texto_mensaje.FontColor = [0.7, 0.2, 0.7];
                drawnow;
                try
                    inecuacion_cuadratica();
                    texto_mensaje.Text = 'Inecuación cuadrática completada.';
                catch
                    texto_mensaje.Text = 'Error: Función inecuacion_cuadratica() no encontrada.';
                    texto_mensaje.FontColor = [0.8, 0.2, 0.2];
                end
                
            otherwise
                texto_mensaje.Text = 'Opción no válida. Intente de nuevo.';
                texto_mensaje.FontColor = [0.8, 0.2, 0.2];
        end
    end
end